trigger:
  branches: { include: [ master ] }
pr: [ master ]

jobs:
- job: build
  displayName: Build
  pool:
    name: 'Hosted Ubuntu 1604'
  workspace:
    clean: all
  steps:
  - task: Gradle@2
    displayName: Gradle build
    inputs:
      gradleWrapperFile: 'gradlew'
      jdkVersionOption: '1.11'
      options: '--no-daemon'
      tasks: 'build javadoc'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'workspace'
      targetPath: '.'

- job: publish
  dependsOn: build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish SNAPSHOT
  pool:
    name: 'Hosted Ubuntu 1604'
  workspace:
    clean: all
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'workspace'
      targetPath: $(System.DefaultWorkingDirectory)
  - bash: ./gradlew --no-daemon -Pversion=$GRADLE_VERSION publish
    env:
      GRADLE_VERSION: 1.0.4.BUILD-SNAPSHOT
      ${{ if not(endsWith(variables['version'], '.RELEASE')) }}:
        GRADLE_PUBLISH_REPO_URL: https://repo.spring.io/libs-snapshot-local/
        GRADLE_PUBLISH_MAVEN_USER: $(artifactory.username)
        GRADLE_PUBLISH_MAVEN_PASSWORD: $(artifactory.password)
